package ru.mrak.codingame.medium.scrabble;

public class Data {
    public static int N = 450;
    public static String DIC =
                    "fawn\n" +
                    "mizzenmast\n" +
                    "snapper\n" +
                    "satire\n" +
                    "nunnery\n" +
                    "pastern\n" +
                    "deferment\n" +
                    "sonja\n" +
                    "circuitry\n" +
                    "hanging\n" +
                    "woody\n" +
                    "houyhnhnm\n" +
                    "aileen\n" +
                    "scold\n" +
                    "originality\n" +
                    "crossbar\n" +
                    "eugenics\n" +
                    "trimester\n" +
                    "appropriation\n" +
                    "rawhide\n" +
                    "fractal\n" +
                    "durocher\n" +
                    "broiler\n" +
                    "wednesday\n" +
                    "woods\n" +
                    "crotch\n" +
                    "steadfastness\n" +
                    "asama\n" +
                    "thrace\n" +
                    "kublai\n" +
                    "precocity\n" +
                    "feasibility\n" +
                    "bannister\n" +
                    "sooth\n" +
                    "selassie\n" +
                    "prosody\n" +
                    "jinrikisha\n" +
                    "dormancy\n" +
                    "centimeter\n" +
                    "cooking\n" +
                    "warmongering\n" +
                    "usenet\n" +
                    "designing\n" +
                    "numeral\n" +
                    "crouch\n" +
                    "china\n" +
                    "chino\n" +
                    "uniroyal\n" +
                    "chink\n" +
                    "doldrums\n" +
                    "existentialist\n" +
                    "cupful\n" +
                    "controversy\n" +
                    "kidd\n" +
                    "neurologist\n" +
                    "climber\n" +
                    "golden\n" +
                    "topography\n" +
                    "projection\n" +
                    "fretwork\n" +
                    "stern\n" +
                    "agassi\n" +
                    "portugal\n" +
                    "insecurity\n" +
                    "cannibal\n" +
                    "inevitable\n" +
                    "definiteness\n" +
                    "music\n" +
                    "crooner\n" +
                    "yahoo\n" +
                    "alphecca\n" +
                    "meteorologist\n" +
                    "adventist\n" +
                    "equilateral\n" +
                    "murchison\n" +
                    "simper\n" +
                    "kampala\n" +
                    "locker\n" +
                    "locket\n" +
                    "busyness\n" +
                    "transom\n" +
                    "wang\n" +
                    "wand\n" +
                    "wane\n" +
                    "fluorite\n" +
                    "disparagement\n" +
                    "titanium\n" +
                    "want\n" +
                    "rayon\n" +
                    "pinto\n" +
                    "cocksucker\n" +
                    "absolute\n" +
                    "travel\n" +
                    "cutback\n" +
                    "propane\n" +
                    "playback\n" +
                    "dangerfield\n" +
                    "canaries\n" +
                    "shirker\n" +
                    "cadence\n" +
                    "barbra\n" +
                    "uselessness\n" +
                    "flossie\n" +
                    "ptarmigan\n" +
                    "apocrypha\n" +
                    "minium\n" +
                    "advancement\n" +
                    "proof\n" +
                    "indulgence\n" +
                    "tar\n" +
                    "earnestness\n" +
                    "tax\n" +
                    "tad\n" +
                    "tag\n" +
                    "kidnapper\n" +
                    "tam\n" +
                    "serial\n" +
                    "tao\n" +
                    "rape\n" +
                    "squealer\n" +
                    "legging\n" +
                    "twizzlers\n" +
                    "jape\n" +
                    "guru\n" +
                    "inaugural\n" +
                    "goldsmith\n" +
                    "panic\n" +
                    "administrator\n" +
                    "hurdler\n" +
                    "heckling\n" +
                    "perjury\n" +
                    "expatriation\n" +
                    "ethnic\n" +
                    "footpath\n" +
                    "skullduggery\n" +
                    "rutledge\n" +
                    "bluebell\n" +
                    "emanuel\n" +
                    "irregularity\n" +
                    "muskogee\n" +
                    "theft\n" +
                    "suharto\n" +
                    "humaneness\n" +
                    "accompanist\n" +
                    "karakul\n" +
                    "obeisance\n" +
                    "gunslinger\n" +
                    "hilary\n" +
                    "ginsu\n" +
                    "dogfish\n" +
                    "reilly\n" +
                    "bye\n" +
                    "jukebox\n" +
                    "contrail\n" +
                    "crash\n" +
                    "nihilist\n" +
                    "flour\n" +
                    "practice\n" +
                    "hygrometer\n" +
                    "flout\n" +
                    "transmitter\n" +
                    "easel\n" +
                    "excitability\n" +
                    "kornberg\n" +
                    "cygnus\n" +
                    "tran\n" +
                    "fiddle\n" +
                    "brontosaurus\n" +
                    "blacktop\n" +
                    "tray\n" +
                    "muralist\n" +
                    "imperiousness\n" +
                    "firepower\n" +
                    "sectional\n" +
                    "category\n" +
                    "semen\n" +
                    "cheekbone\n" +
                    "billfold\n" +
                    "grits\n" +
                    "zimmerman\n" +
                    "sacrifice\n" +
                    "proviso\n" +
                    "dictionary\n" +
                    "digitalis\n" +
                    "abductor\n" +
                    "diva\n" +
                    "obliteration\n" +
                    "yore\n" +
                    "kipper\n" +
                    "fitzpatrick\n" +
                    "conversation\n" +
                    "calvary\n" +
                    "cain\n" +
                    "ionic\n" +
                    "boondoggle\n" +
                    "firehouse\n" +
                    "bleakness\n" +
                    "harmlessness\n" +
                    "probation\n" +
                    "endemic\n" +
                    "salient\n" +
                    "droop\n" +
                    "intention\n" +
                    "nomination\n" +
                    "overdraft\n" +
                    "myspace\n" +
                    "galley\n" +
                    "triumvirate\n" +
                    "anaemia\n" +
                    "motorcar\n" +
                    "drool\n" +
                    "dschubba\n" +
                    "transubstantiation\n" +
                    "constituent\n" +
                    "institution\n" +
                    "bismuth\n" +
                    "enticement\n" +
                    "clemson\n" +
                    "sculpture\n" +
                    "bodice\n" +
                    "lateness\n" +
                    "alfonso\n" +
                    "muezzin\n" +
                    "agronomy\n" +
                    "florin\n" +
                    "agency\n" +
                    "bagel\n" +
                    "sindhi\n" +
                    "wetback\n" +
                    "gracelessness\n" +
                    "optometry\n" +
                    "siphon\n" +
                    "noggin\n" +
                    "deena\n" +
                    "fortieth\n" +
                    "weeper\n" +
                    "dent\n" +
                    "dena\n" +
                    "deng\n" +
                    "fief\n" +
                    "myrna\n" +
                    "aquafresh\n" +
                    "seaweed\n" +
                    "chicken\n" +
                    "debate\n" +
                    "brainteaser\n" +
                    "dandruff\n" +
                    "moet\n" +
                    "storekeeper\n" +
                    "cache\n" +
                    "ninepin\n" +
                    "forfeit\n" +
                    "daydreamer\n" +
                    "sagittarius\n" +
                    "silas\n" +
                    "dope\n" +
                    "inseam\n" +
                    "watercolor\n" +
                    "ophthalmology\n" +
                    "suet\n" +
                    "ghetto\n" +
                    "heretic\n" +
                    "expertness\n" +
                    "netzahualcoyotl\n" +
                    "handspring\n" +
                    "jaime\n" +
                    "quaternary\n" +
                    "proprietorship\n" +
                    "sediment\n" +
                    "inconspicuousness\n" +
                    "goldfinch\n" +
                    "ebb\n" +
                    "bekesy\n" +
                    "churchman\n" +
                    "gerrymander\n" +
                    "criminologist\n" +
                    "weller\n" +
                    "caginess\n" +
                    "closet\n" +
                    "genius\n" +
                    "panty\n" +
                    "linebacker\n" +
                    "caracul\n" +
                    "foetus\n" +
                    "addie\n" +
                    "salesgirl\n" +
                    "spoil\n" +
                    "dependance\n" +
                    "memento\n" +
                    "barrett\n" +
                    "soapbox\n" +
                    "wilbur\n" +
                    "profanity\n" +
                    "heterosexuality\n" +
                    "broadside\n" +
                    "grain\n" +
                    "canopy\n" +
                    "premise\n" +
                    "hyphen\n" +
                    "neighborliness\n" +
                    "fishhook\n" +
                    "softie\n" +
                    "window\n" +
                    "reindeer\n" +
                    "cordite\n" +
                    "emirate\n" +
                    "zenger\n" +
                    "verizon\n" +
                    "butchery\n" +
                    "buffy\n" +
                    "shuttlecock\n" +
                    "waggle\n" +
                    "repetition\n" +
                    "rasher\n" +
                    "kerchief\n" +
                    "wilt\n" +
                    "vanilla\n" +
                    "cursor\n" +
                    "wild\n" +
                    "wile\n" +
                    "hobbyhorse\n" +
                    "jehovah\n" +
                    "ideogram\n" +
                    "whorl\n" +
                    "whore\n" +
                    "vintage\n" +
                    "headlight\n" +
                    "fomentation\n" +
                    "zilch\n" +
                    "firmament\n" +
                    "parthenon\n" +
                    "premiere\n" +
                    "diploma\n" +
                    "octagon\n" +
                    "issuance\n" +
                    "antipasto\n" +
                    "overwork\n" +
                    "declamation\n" +
                    "english\n" +
                    "breaker\n" +
                    "rocker\n" +
                    "rocket\n" +
                    "boot\n" +
                    "wren\n" +
                    "miniscule\n" +
                    "happiness\n" +
                    "temerity\n" +
                    "disturbance\n" +
                    "harare\n" +
                    "sky\n" +
                    "micronesia\n" +
                    "sweetener\n" +
                    "thermodynamics\n" +
                    "adoption\n" +
                    "ski\n" +
                    "armonk\n" +
                    "knob\n" +
                    "saturation\n" +
                    "branch\n" +
                    "knot\n" +
                    "alisha\n" +
                    "obliqueness\n" +
                    "iberia\n" +
                    "pygmalion\n" +
                    "cutlet\n" +
                    "hitchhike\n" +
                    "dancer\n" +
                    "nominative\n" +
                    "lance\n" +
                    "sequence\n" +
                    "dispossession\n" +
                    "birthmark\n" +
                    "eventfulness\n" +
                    "preposition\n" +
                    "holler\n" +
                    "empire\n" +
                    "holley\n" +
                    "leaf\n" +
                    "lead\n" +
                    "zanuck\n" +
                    "leak\n" +
                    "lean\n" +
                    "lear\n" +
                    "leap\n" +
                    "friskiness\n" +
                    "saltcellar\n" +
                    "voluptuousness\n" +
                    "leader\n" +
                    "haywood\n" +
                    "murderer\n" +
                    "thoroughfare\n" +
                    "slur\n" +
                    "mitt\n" +
                    "slut\n" +
                    "wesley\n" +
                    "corpuscle\n" +
                    "mite\n" +
                    "slug\n" +
                    "slue\n" +
                    "throne\n" +
                    "throng\n" +
                    "incline\n" +
                    "hausdorff\n" +
                    "biscuit\n" +
                    "dependence\n" +
                    "shipping\n" +
                    "sidekick\n" +
                    "uccello\n" +
                    "dependency\n" +
                    "epiphany\n" +
                    "lardner\n" +
                    "warranty\n" +
                    "bugle\n" +
                    "hotcake\n" +
                    "headphone\n" +
                    "brush\n" +
                    "registration\n" +
                    "maize\n" +
                    "grapevine\n" +
                    "preferment\n" +
                    "hypnotism\n" +
                    "footwork\n" +
                    "clampdown\n" +
                    "wight\n" +
                    "brashness\n" +
                    "nassau\n" +
                    "goose\n" +
                    "tab\n" +
                    "daffodil\n" +
                    "gelatine\n" +
                    "windfall\n" +
                    "benetton\n" +
                    "hilfiger\n" +
                    "jewel\n" +
                    "horsewoman\n" +
                    "dearth\n" +
                    "carbohydrate\n" +
                    "hardiness\n" +
                    "goodness\n" +
                    "attributive\n" +
                    "boor\n" +
                    "percent\n" +
                    "illinois\n" +
                    "book\n" +
                    "boom\n" +
                    "boon\n" +
                    "boob\n" +
                    "malefactor\n" +
                    "junk\n" +
                    "juno\n" +
                    "xenon\n" +
                    "june\n" +
                    "jung\n" +
                    "sherd\n" +
                    "dissension\n" +
                    "sheri\n" +
                    "emery\n" +
                    "flatfish\n" +
                    "northerly\n" +
                    "jawbone";
    public static String LETTERS = "retpasn";
}
